### ISSUE TITLE
Which files need to be hosted

### ISSUE THREAD

**Issue by pvnr0082t** [inexorabletash/polyfill#102]
Hi @inexorabletash ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this lib in cdnjs.
I know `polyfill.js` and `polyfill.min.js` need to be hosted for sure. Could you please tell me if there is any other files need to be added?
Thank you.

https://github.com/cdnjs/cdnjs/issues/7508

**Comment by inexorabletash** [comment]
Sorry for the delay - was travelling.

`polyfill.js` and `polyfill.min.js` are probably the only two that developers should be relying on. Let's start there and see who complains.

**Comment by pvnr0082t** [comment]
No problem.

Thank you for your help. :facepunch:
