### ISSUE TITLE
Publish the latest version on NPM

### ISSUE THREAD

**Issue by pvnr0082t** [inexorabletash/polyfill#103]
Hi @inexorabletash ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team. I found that the latest version is v0.1.20 but it is still v0.1.19 on npm. Could you please publish the latest version on npm? thank you.

https://github.com/cdnjs/cdnjs/issues/7508

**Comment by inexorabletash** [comment]
Done, thanks. It's now v0.1.21 to pick up a few more fixes.

**Comment by cheton** [comment]
May I know when will this commit (https://github.com/inexorabletash/polyfill/commit/16b9cf934689bed4a1537f6aa19cc61aefe24f5b - Add ChildNode/ParentNode mixins to DOM) be published to NPM?

**Comment by inexorabletash** [comment]
Huh, I thought I'd published since then. :(

Will do one I'm home from a conference.

**Comment by inexorabletash** [comment]
Should be published as 0.1.26

**Comment by cheton** [comment]
Great!
