### ISSUE TITLE
Assertion messages fill out the console if script is minified

### ISSUE THREAD

**Issue by ardevelop** [inexorabletash/polyfill#108]
Assertion messages fill out the console if script is minified, they distract attention from real errors.

![image](https://cloud.githubusercontent.com/assets/1272897/20058384/71b501e2-a4f9-11e6-8bf3-2a034887d1b7.png)

**Comment by inexorabletash** [comment]
You can comment out the assertion lines, or (as I do) use a minifier that elides console.assert() calls. For example, with uglifyjs: `uglifyjs [input files] --compress drop_console`
