### ISSUE TITLE
keyFixTable needs to be updated for older browsers.

### ISSUE THREAD

**Issue by AkshayDhankhar** [inexorabletash/polyfill#110]
As per documentation key varies in browser and keyFixTable needs to be updated.

Older browsers may return "Spacebar" instead of " " for the Space Bar key. Firefox did so until version 37, as did Internet Explorer 9.

While older browsers used words like "Add", "Decimal", "Multiply", and so forth modern browsers identify these using the actual character ("+", ".", "*", and so forth) 

![space_in_chrome](https://cloud.githubusercontent.com/assets/10391002/21140048/4a8481b6-c136-11e6-96e0-58705a2b0325.png)

![space_in_ie](https://cloud.githubusercontent.com/assets/10391002/21140054/4f44f032-c136-11e6-8b7a-c86759763088.png)

**Comment by inexorabletash** [comment]
Thanks for the report and fix! I've tagged/published v0.1.28

**Comment by AkshayDhankhar** [comment]
@inexorabletash Thanks..:)
