### ISSUE TITLE
An error ("fetch is not defined") occurs when include polyfill.min.js

### ISSUE THREAD

**Issue by boringer** [inexorabletash/polyfill#112]
However, it works fine with polyfill.js.

**Comment by inexorabletash** [comment]
What browser and version does this appear in?

**Comment by boringer** [comment]
Android 6.0, WeChat webview, which maybe you don't use.

I `try-catch` it and caught something like `Internal assertion failure: Expected function name "includes", was ""`.

By the way, I saw URL and fetch appear twice in polyfill, does that matter?

![1](https://cloud.githubusercontent.com/assets/14685751/21211316/8fe4e812-c2bd-11e6-9730-ceab18fb38bf.png)

![2](https://cloud.githubusercontent.com/assets/14685751/21211317/90264faa-c2bd-11e6-9f56-02b97263218d.png)

**Comment by inexorabletash** [comment]
> I saw URL and fetch appear twice in polyfill, does that matter?

Wow, thanks, I had those listed twice in a pre-commit hook. Fixed in 3bdeabbe486ba65273044dee79dc880e129a10c2

**Comment by inexorabletash** [comment]
Thank you __VERY__ much for this report. I missed it because it only occurred in browsers without `Array.prototype.includes` when minified - I should have caught that earlier. :(

I pushed a new release with the fix: v0.1.29
