### ISSUE TITLE
Errors in IE 8

### ISSUE THREAD

**Issue by boringer** [inexorabletash/polyfill#113]
"Symbol is null, not defined or not a function" at polyfill.min.js: 1, 15232.

"Document is not defined" at polyfill.js: 5116.

**Comment by inexorabletash** [comment]
b59adb55369b022d1bb0009367e524b1aa2dc42a should take care of the "Document is not defined". I'll have to poke at the Symbol issue a bit more - does it occur in the non-minimized script?

**Comment by boringer** [comment]
No.

And I print `t` after `t.Symbol=n` in polyfill.min.js (same as `global.Symbol = Symbol` in polyfill.js), the result seems to be function `raw`, which is object `window` in other browsers.

My English sucks, did I make it clear?

**Comment by inexorabletash** [comment]
Sounds like a minifier bug. I'll update to the latest.

**Comment by inexorabletash** [comment]
I think this was fixed in 0959c790d179856d028c9bacb8f0488b26568f02 - I added `--support-ie8` to the options passed to Uglify (the minifier). This seems to have resolved issues when testing w/ IE11 in IE8 mode.

@boringer - Can you please verify?

**Comment by boringer** [comment]
Works well now. Thank you.
