### ISSUE TITLE
Feature Request: pass object and array of arrays to the URLSearchParams constructor

### ISSUE THREAD

**Issue by vkrol** [inexorabletash/polyfill#119]
Hello!

The URL specification was updated recently. Now we can pass an object or an array of arrays to the URLSearchParams constructor.

https://github.com/whatwg/url/commit/31ddc5bd0c4ca1b6d837029c926ec87bc472c168
https://url.spec.whatwg.org/#interface-urlsearchparams

It would be great if the polyfill will support this feature.

Thanks!

**Comment by inexorabletash** [comment]
Thanks for pointing this out! Can you give the latest code a try?

Since existing native implementations (e.g. in Chrome) don't support this yet I override the constructor in those cases.

Assuming this seems acceptable I'll push a new release.

**Comment by vkrol** [comment]
@inexorabletash this is awesome! Thanks.

**Comment by Mouvedia** [comment]
> I override the constructor in those cases.

So it's ponyfill then?

**Comment by vkrol** [comment]
@inexorabletash 

> Assuming this seems acceptable I'll push a new release.

When you want to push a new release? 😃
