### ISSUE TITLE
Obsolete not available through NPM?

### ISSUE THREAD

**Issue by sunny-g** [inexorabletash/polyfill#121]
Is there a reason that the scripts contained within `obsolete/` are not included for distribution in NPM?

**Comment by inexorabletash** [comment]
Like `experimental/` they're by definition not defined by the Web platform and hence shouldn't be relied on. If included, someone would rely on them. The point of polyfills is that eventually the browsers catch up and the polyfills can be dropped. If something isn't on track for that it doesn't belong in the polyfill. 

(In hindsight I regret _ever_ publishing to NPM, and definitely don't want to increase the surface area with unstable, non-standard behaviors.)

**Comment by sunny-g** [comment]
@inexorabletash makes sense, I wanted to use the storage polyfills for private browsing in Safari and in iOS (since they are disabled and it seems they may never be "polyfilled"), but thanks anyways!
