### ISSUE TITLE
URLSearchParams constructor fails when passed an existing instance

### ISSUE THREAD

**Issue by triblondon** [inexorabletash/polyfill#125]
Test:

```
>>> var sp1 = new URLSearchParams('a=1');
>>> String(sp1)
"a=1"
>>> var sp2 = new URLSearchParams(sp1);
>>> String(sp2)
"_list=%5Bobject+Object%5D&_url_object=null&_setList=function+(list)+%7B+if+(!updating)+%24this._list+%3D+list%3B+%7D&_update_steps=function()+%7B%0A++++++++if+(updating)+return%3B%0A++++++++updating+%3D+true%3B%0A%0A++++++++if+(!%24this._url_object)+return%3B%0A%0A++++++++%2F%2F+Partial+workaround+for+IE+issue+with+'about%3A'%0A++++++++if+(%24this._url_object.protocol+%3D%3D%3D+'about%3A'+%26%26%0A++++++++++++%24this._url_object.pathname.indexOf('%3F')+!%3D%3D+-1)+%7B%0A++++++++++%24this._url_object.pathname+%3D+%24this._url_object.pathname.split('%3F')%5B0%5D%3B%0A++++++++%7D%0A%0A++++++++%24this._url_object.search+%3D+urlencoded_serialize(%24this._list)%3B%0A%0A++++++++updating+%3D+false%3B%0A++++++%7D"
```

Expected: `a=1`

Broken by commit: https://github.com/inexorabletash/polyfill/commit/c3c8bff6c85d94b4a951adfc7941556619667059#diff-07fa9a7ce00e46c7d975483d790d7cee

Demo (uses test suite from polyfill.io):
http://jsbin.com/biwopam/36/edit

Tested in: IE 11 (errors as above), Opera 12 (errors as above), Safari 10 (works as expected)

**Comment by triblondon** [comment]
On further investigation it seems it [works when the es6.js bundle is also loaded](http://jsbin.com/biwopam/118/edit).  That's unfortunate for polyfill.io because we serve polyfills individually rather than in big bundles.  Is it possible to identify which bit of ES6 is needed by the change made in [this commit](https://github.com/inexorabletash/polyfill/commit/c3c8bff6c85d94b4a951adfc7941556619667059#diff-07fa9a7ce00e46c7d975483d790d7cee)?  If so we can add just that feature as a dependency of the URL polyfill.

**Comment by inexorabletash** [comment]
Works in an ES6 environment or with the es6.js polyfill, but yeah, I can fix.

**Comment by inexorabletash** [comment]
@triblondon Can you try tip-of-tree? If you verify the fix I'll push a new version.

**Comment by triblondon** [comment]
Trying...

**Comment by triblondon** [comment]
Verified: http://jsbin.com/biwopam/127/edit

**Comment by inexorabletash** [comment]
Pushed a new version. Sorry about that! Thanks for the bug report.

**Comment by triblondon** [comment]
Splendid, thanks for that.
