### ISSUE TITLE
got an error when execute in the console

### ISSUE THREAD

**Issue by zzzgit** [inexorabletash/polyfill#129]
<script src="https://cdn.rawgit.com/inexorabletash/polyfill/v0.1.33/polyfill.min.js"></script>
I add this in the html,it perform well.
but,if i copy the content of this js file and post it to the console,and then execute them,I will get an error
why and how?

**Comment by inexorabletash** [comment]
What browser, and what is the error?

Do you get the error in the non-minified version? If so, have you tried bisecting (i.e. delete chunks until the error stops happening) ?

**Comment by zzzgit** [comment]
IE11,polyfill.js also got an error

the error is can not get "toString" of undefined or null

**Comment by inexorabletash** [comment]
The problem doesn't occur for me. I suggest trying the files that are composited into polyfill.js one by one (html.js dom.js xhr.js cssom.js url.js fetch.js es5.js es6.js es2016.js) and see if you can narrow down the problem.

Note that consoles are "weird" so this may be console-specific and thus not affect actual behavior within pages.
