### ISSUE TITLE
Keyboard `Unidentified` for keyCode 252

### ISSUE THREAD

**Issue by daneren2005** [inexorabletash/polyfill#130]
When a user types in keyCode 252 the key is being polyfilled to `Unidentified` instead of `ü`.  This is probably a problem for more than just this one character.  I feel like a better work around would be to fallback to the existing `event.key` if one exists.  That would make it so at least the polyfill won't remove support for keyCode's which modern browsers understand.

**Comment by inexorabletash** [comment]
Hmmm... if `key` is present on the event it should be used as-is, apart from "fixes". What browser are you testing in? How are you using the polyfill?

**Comment by inexorabletash** [comment]
Ping - what browser is being used here?

**Comment by daneren2005** [comment]
I honestly don't remember at this point.  I'm not sure why I didn't see the notification when you first asked back in May.

**Comment by inexorabletash** [comment]
No worries. If you're able to repro, please let me know.
