### ISSUE TITLE
Cannot assign to read only property DOM_KEY_LOCATION_STANDARD

### ISSUE THREAD

**Issue by davisford** [inexorabletash/polyfill#131]
`Uncaught TypeError: Cannot assign to read only property 'DOM_KEY_LOCATION_STANDARD' of function 'function KeyboardEvent() { [native code] }'`

Getting this err on Chrome 59.x -- bundling with webpack.  Have you seen this before?

**Comment by inexorabletash** [comment]
Thanks - it was assigning to a read-only property (as it says) which throws in strict mode, presumably being introduced by webpack. I fixed it.

Let me know if this solves the problem for you and I can spin a release.
