### ISSUE TITLE
Why a unlicense for a polyfills library ?

### ISSUE THREAD

**Issue by Lcfvs** [inexorabletash/polyfill#136]
It isn't exactly the opposite of the philosophy of the polyfills ?

**Comment by inexorabletash** [comment]
So far as I am led to believe, the Unlicense is the closest thing to CC0 for code: do with as you will, no restrictions. No need to give attribution or require retaining the same license.

**Comment by Lcfvs** [comment]
Oh, ok, sorry for my misunderstood 👍
