### ISSUE TITLE
Exception thrown and not caught when loading es6 in IE9

### ISSUE THREAD

**Issue by cyberwombat** [inexorabletash/polyfill#137]
Using this in head:

```
<script src="https://cdn.rawgit.com/inexorabletash/polyfill/9119cb08/es5.js"></script>
<script src="https://cdn.rawgit.com/inexorabletash/polyfill/9119cb08/es6.js"></script>
  
```
In IE9 (9.0.8112) in Win7 dumps this error to console on load.

```
SCRIPT5022: Exception thrown and not caught 
es6.js, line 285 character 9
```

**Comment by inexorabletash** [comment]
Can you provide a stack trace? That's the polyfill for Symbol.prototype.valueOf() throwing.

It's unclear what would be triggering that, and I don't have IE9 handy.

**Comment by gonegreen** [comment]
Hmm IE9 doesn't have proper stack trace. Under its Call Stack panel it mentions this line right before the valueOf one:

 console.assert(typeof global.Symbol() === 'symbol' || symbolForKey(String(global.Symbol('x')))); // Line 302

Not sure if I am reading it correctly and if it's the one triggering the error

**Comment by cyberwombat** [comment]
Hmm IE9 doesn't have proper stack trace. Under its Call Stack panel it mentions this line right before the valueOf one:

console.assert(typeof global.Symbol() === 'symbol' || symbolForKey(String(global.Symbol('x')))); // Line 302

Not sure if I am reading it correctly and if it's the one triggering the error

**Comment by inexorabletash** [comment]
Finally had a chance to try this out; I pushed a fix. Can you give it a try?

**Comment by Mouvedia** [comment]
@inexorabletash check https://github.com/inexorabletash/polyfill/commit/9f7d4168657e2c164d647a6959f402f2c33eb5b4#commitcomment-25117075
