### ISSUE TITLE
URL polyfill does not work in Opera Mini 8

### ISSUE THREAD

**Issue by JakeChampion** [inexorabletash/polyfill#138]
I got the Opera Mini 8 emulator from https://dev.opera.com/articles/installing-opera-mini-on-your-computer/ and then visited https://inexorabletash.github.io/polyfill/tests/url.html in the browser.

<details><summary>Click here to see the screenshots of the failing tests, most are for Base URL.
</summary>
<img src=https://user-images.githubusercontent.com/1569131/31971222-c0defae2-b912-11e7-9829-494ca1c9a16a.png>
<img src=https://user-images.githubusercontent.com/1569131/31971224-c10c42ae-b912-11e7-9b44-eae7355fe5e1.png>
<img src=https://user-images.githubusercontent.com/1569131/31971225-c13bb426-b912-11e7-9045-30fdba263837.png>
<img src=https://user-images.githubusercontent.com/1569131/31971226-c167c7aa-b912-11e7-9b68-567eeebbb817.png>
</details>

**Comment by inexorabletash** [comment]
Do you know if the polyfill for URL is being used (and the logic to handle the base parameter is failing) or if there's a native implementation (and its base parameter handling is buggy) ?

Either way, I'll take a peek.

**Comment by JakeChampion** [comment]
The polyfill is being used, yes. Here is a screenshot of the browser running the web-platform-tests for url constructor and showing that they all fail (the one passing test is showing the test harness is working).

<img width="1440" alt="screen shot 2017-10-25 at 00 55 11" src="https://user-images.githubusercontent.com/1569131/31973681-46d3e5ac-b91f-11e7-9b10-d4f895355b6e.png">

**Comment by inexorabletash** [comment]
Okay - thanks for the excellent steps, I was able to repro. It may be a few days before I'm able to spend time to debug it though.

**Comment by inexorabletash** [comment]
It appears that in Opera Mini, in the document constructed with `document.implementation.createHTMLDocument`, the `<base href>` is ignored.

Using an `iframe` works. That's a bit heavy weight, so a workaround scoped to Opera Mini might be appropriate.

**Comment by inexorabletash** [comment]
Give ff5329920cc8fe7037b88b975628fe050f33f8bb a try ?

**Comment by JakeChampion** [comment]
![screen shot 2017-10-26 at 17 32 03](https://user-images.githubusercontent.com/1569131/32065098-a63f006c-ba73-11e7-9ad9-da19e2440018.png)

Nice work! All the base url tests pass! 👍

**Comment by inexorabletash** [comment]
Also, for completely unrelated reasons, thanks for indirectly pointing me at __microemu__ !
