### ISSUE TITLE
Infinite loop in HasProperty

### ISSUE THREAD

**Issue by mcalmus** [inexorabletash/polyfill#145]
I'm getting an infinite loop with HasProperty when using with IE8.

the call to "o = Object.getPrototypeOf(o);" is returning the same value as was passed in (polyfill from core-js). Perhaps the code could be changed to:

      var newO = Object.getPrototypeOf(o);
      if (newO === o) break;
      else o = newO;

**Comment by mcalmus** [comment]
The code I submitted may not work. In the debugger I'm seeing that:

o.constructor.prototype for [] returns [].

However, I don't know whether the empty array returned is the same object as the one passed in. It may need to be == rather than ===.

**Comment by inexorabletash** [comment]
Thanks. I'll try to get a fix in soon.

What's an example object you're seeing in IE8 that is its own prototype?

**Comment by mcalmus** [comment]
This was happening with an array. I tested in the scratchpad. The prototype of an empty array is different from the empty array, but the prototype of that is itself.

**Comment by inexorabletash** [comment]
Ah yes: in IE8 this is true:

`Object.getPrototypeOf([]) === Object.getPrototypeOf(Object.getPrototypeOf([]))`

**Comment by inexorabletash** [comment]
Should be fixed in beafb246d4ad04703ecddf2c78377b9af05bd6c5

**Comment by mcalmus** [comment]
Confirmed. Thanks.

**Comment by inexorabletash** [comment]
Oh, one thing I didn't do was add a test. Bad me.

How were you actually running into this, i.e. what polyfilled method was calling HasProperty? Array.prototype.find or something?

**Comment by mcalmus** [comment]
I'm trying to polyfill enough to get IE8 working within an Angular app. I
think it was calling a getProperty method somewhere, but it wasn't in my
code it was in library code. From the call stack it looks like it was doing
an array find call from a require call.
