### ISSUE TITLE
License

### ISSUE THREAD

**Issue by brettz9** [inexorabletash/polyfill#146]
Hi,

Some have expressed concern with the Unlicense: https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense?rq=1

Might you consider dual-licensing as MIT? (I'm interested in the ChildNode/ParentNode polyfills in particular atm...)

**Comment by inexorabletash** [comment]
Sure - I wanted it to be as restriction-free as possible, but it seems like there's no way to do that with a single license in all jurisdictions. *sigh*

File a PR?
