### ISSUE TITLE
Add MouseEvent.offsetX/Y polyfill for FF

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/polyfill#45]

**Comment by Yaffle** [comment]
https://gist.github.com/Yaffle/1145197 - can this help ?
`var offsetXY = convertPointFromPageToNode(event.target, event.pageX, event.pageY)`

**Comment by inexorabletash** [comment]
Cool, I'll take a look!

Not sure I want to roll this into the polyfills, but i might snag i for a different hobby project, at least.

**Comment by inexorabletash** [comment]
FF now supports offsetX/offsetY natively, so closing this out.
