### ISSUE TITLE
XHR Event polyfill

### ISSUE THREAD

**Issue by stuartpb** [inexorabletash/polyfill#49]
XMLHttpRequest, in the latest specs and browsers, supports more events than "readystatechange" (namely "error", "abort", "timeout", and "load"), and supports adding listeners using addEventListener rather than just setting the "onreadystatechange" property: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#Events

It would be nice if web developers could have a polyfill that allows us to rely on the presence of these events and not worry about our code breaking on IE9.

**Comment by inexorabletash** [comment]
XHR's a dead end anyway. `fetch()` is the new hotness.

**Comment by tracker1** [comment]
+1 to close in favor of the [fetch polyfill](https://github.com/github/fetch)

**Comment by inexorabletash** [comment]
Or https://github.com/inexorabletash/polyfill/blob/master/experimental/fetch.js

**Comment by cvrebert** [comment]
Yup. https://fetch.spec.whatwg.org/#fetch-api
