### ISSUE TITLE
KeyboardEvent.key polyfill

### ISSUE THREAD

**Issue by simonzack** [inexorabletash/polyfill#52]
I was rather excited to see an up-to-date KeyboardEvent polyfill, but was surprised that `key` was not implemented.

Firefox 37 is set to support this properly and chrome just had a commit a couple days ago in master, so this is still not widely supported. I see that `char` and `code` are supported, but `key` feels a lot more natural in my application.

It would be nice to have this.

**Comment by inexorabletash** [comment]
*sigh* Spec changed since I last looked. Looks like `key` is back in there per:

https://dvcs.w3.org/hg/dom3events/raw-file/tip/html/DOM3-Events.html#interface-KeyboardEvent

I'll see what I can do.

**Comment by inexorabletash** [comment]
fb96c0c29c2735db4d567b63a3d4762c2920d0b4 should do it, although obviously it entirely depends on keyboard layout. but so does the whole polyfill, so... give it a whirl.

**Comment by simonzack** [comment]
Thanks!
