### ISSUE TITLE
keyboardevent.key fixing

### ISSUE THREAD

**Issue by flying-sheep** [inexorabletash/polyfill#53]
hi, for firefox, the code seems to use the `KeyboardEvent.key` property if existing, but that one isn’t supported fully.

e.g. firefox uses (until version 37 lands) `"Down"` instead of `"ArrowDown"` etc.

**Comment by inexorabletash** [comment]
Please double check. The ones I could identify as changing are:

`Up` => `ArrowUp`, `Down` => `ArrowDown`, `Left` => `ArrowLeft`, `Right` => `ArrowRight`
`Esc` => `Escape`, `Del` => `Delete`

I'm less sure about these:

`Shift` => `ShiftLeft`/`ShiftRight`
`Alt` => `AltLeft`/`AltRight`
`Control` => `ControlLeft`/`ControlRight`
`Meta` => `OSLeft`/`OSRight`

http://www.w3.org/TR/DOM-Level-3-Events-code/ seems to indicate `ShiftLeft` etc would be the name. But sending `key: Shift` and `location: 1` makes more sense. (Not that the web makes sense...)

**Comment by inexorabletash** [comment]
Based on https://dvcs.w3.org/hg/dom3events/raw-file/tip/html/DOM3Events-key.html I think I need to revisit `OS` vs `Meta`

**Comment by flying-sheep** [comment]
thank you!

[this](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent.key#Key_values) page has a good overview (hint: it’s a fucking mess!)

**Comment by inexorabletash** [comment]
Thanks for the link! I reviewed the specs again:

https://dvcs.w3.org/hg/dom3events/raw-file/tip/html/DOM3Events-code.html
https://dvcs.w3.org/hg/dom3events/raw-file/tip/html/DOM3Events-key.html

.. and updated the "fix" table and believe I have the OS/Meta thing sorted out too.
