### ISSUE TITLE
URL: base and bad URL

### ISSUE THREAD

**Issue by monolithed** [inexorabletash/polyfill#56]
From [spec](https://url.spec.whatwg.org/#url-parsing) 

1. 

```
Constructor(USVString url, optional USVString base = "about:blank")
```

2.
```
If url is failure, return failure.
```

In other words `new URL('')` should throw an exception like Firefox

**Comment by inexorabletash** [comment]
Presumably you're testing in Chrome? If the browser supports the URL constructor natively, the polyfill falls back to that. And `new URL('')` doesn't throw in Chrome.

I agree that, per current spec, it should: `about:blank` is not a relative scheme, so it should hit the failure case you cite.

**Comment by monolithed** [comment]
Yup, Chrome disappointed me (

**Comment by inexorabletash** [comment]
FYI, I filed http://crbug.com/463961 against Chrome to track this.

**Comment by monolithed** [comment]
Thx!

**Comment by inexorabletash** [comment]
Quick note: a fix for the issue landed in Chrome. Should appear in Chrome 49 unless the change is reverted for some reason.

**Comment by inexorabletash** [comment]
Yep, `new URL('')` now throws in Chrome 49. Closing this out.
