### ISSUE TITLE
Why dataset polyfill doesn't work properly in IE8?

### ISSUE THREAD

**Issue by thednp** [inexorabletash/polyfill#60]
Just askin, maybe I'm using it wrong but I get Obj.dataset undefined in IE8 in compatibility mode Windows8.

**Comment by thednp** [comment]
IE8 is so damn stupid confusing this with self. man...

**Comment by tracker1** [comment]
@thednp `window` is the global variable in the browser... `self` will resolve to `window.self`, which is also the default runtime context in JS (`this`) for scripts.... ergo: `(self === this) //true` ... if you have a browser that doesn't do that, I'd be slightly surprised.

**Comment by thednp** [comment]
I discovered that the e.target was a <span> instead of it's parent <a>, and unlike the parent, didn't have dataset so my handler was always going the wrong way in IE8. With jQuery the event is automatically delegated properly to children where with native js it's not.
