### ISSUE TITLE
[Question] do you consider hosting your files on CDN?

### ISSUE THREAD

**Issue by thednp** [inexorabletash/polyfill#62]
I tested with other stuff like https://cdn.polyfill.io/v1/docs/ and yours is better, it's a bit larger as it includes all the stuff, the other is automatic or some sort, claims to be lighter and specific to each browser, but I am getting some errors with it's classList when used alone or poor performance on IE9 when used normally with all IE9 requested polyfilles, perhaps it's how it is...

Anyways, yours is the best! When do we have a(some) CDN link(s)? 

(polyfill.js / js.js | web.js | dom.js)

**Comment by huei90** [comment]
+1 for public CDN.

**Comment by thednp** [comment]
I added my project to jsdelivr today and I am happy, you should also commit yours too, it's cool. (Don't forget to add CustomEvent :P)
