### ISSUE TITLE
Keyboard example broken on MSIE8

### ISSUE THREAD

**Issue by IvanSanchez** [inexorabletash/polyfill#63]
When trying out the keyboard example (http://inexorabletash.github.io/polyfill/demos/keyboard.html) on MSIE8, it crashes and the following messages are displayed on the developer's console:

```
  Object doesn't support this property or method  web.js, line 19 character 3
  Exception thrown and not caught  keyboard.js, line 2 character 77
  'document.body.classList' is null or not an object  keyboard_test.js, line 4 character 3
```

The first and third can be fixed by switching the loading order of ```es5.js```, whereas the error in ```keyboard.js``` has to do with the stub ```global.KeyboardEvent``` definition. I tried working around the latter with little success.

This is reproducible in my MSIE8 virtual machine from www.modern.ie.

**Comment by inexorabletash** [comment]
Thanks, I'll take a look

**Comment by inexorabletash** [comment]
Should be fixed now - please give it a try?

**Comment by IvanSanchez** [comment]
Seems to work perfectly on MSIE8 now :+1:
