### ISSUE TITLE
Please add Event and CustomEvent

### ISSUE THREAD

**Issue by thednp** [inexorabletash/polyfill#64]
I tried to do this myself but I get an error.

Thank you

**Comment by inexorabletash** [comment]
Can you give me an example usage that you're trying to enable?

**Comment by thednp** [comment]
Yes.

<pre>
//creating the event
var slide = new CustomEvent("slide.bs.carousel");

//trigger the event
element.dispatchEvent(slide)
</pre>

This didn't work with your polyfill.

**Comment by thednp** [comment]
Any news on this? I ask because I referenced your polyfill on <a href="http://thednp.github.io/Native-Javascript-for-Bootstrap/">my project demo page</a>, and CustomEvent is required for the Carousel script. 
Or at least give me an example on how to include the above polyfill into yours.

Thanks again.

**Comment by inexorabletash** [comment]
If you want to implement, add tests, and send a pull request I can take a look. It's not something I've needed for my projects so I haven't spent any time on it, nor am I likely to any time soon.

It looks like there are some CustomEvent polyfills kicking around on the web, e.g.:

http://stackoverflow.com/questions/14358599/object-doesnt-support-this-action-ie9-with-customevent-initialization

The way that my (and most) polyfills are written they should be reasonably independent of each other, so you can probably just have a standalone definition for CustomEvent, e.g.:

```js
(function(global) {
  function CustomEvent(...) { /* polyfill code here */ };
  if (!('CustomEvent' in global))
    global.CustomEvent = CustomEvent;
}(self));
```

**Comment by thednp** [comment]
I just tried that and it throws "createEvent is not supported." 

Looking for another way.
