### ISSUE TITLE
native TypeArray works differently

### ISSUE THREAD

**Issue by Yaffle** [inexorabletash/polyfill#66]
var x = new g.Float64Array(1);
var y = new g.Int32Array(x.buffer);
x[0] = Number.MAX_VALUE / 2;
console.log(y[0]);
console.log(y[1]);

P.S. 
the exponent calculation looks strange

**Comment by inexorabletash** [comment]
The polyfill is big-endian. Most implementations are little-endian.

Otherwise... it looks like the rounding might be slightly different.

**Comment by inexorabletash** [comment]
More minimal example, ignoring the endianness:

```js
var x = new Float64Array(1);
x[0] = Number.MAX_VALUE / 2;
console.log(x[0] - Number.MAX_VALUE / 2);
```

**Comment by Yaffle** [comment]
ok,
it does not matter anyway
sorry for the issue

**Comment by inexorabletash** [comment]
Thanks for the PR! Merged
