### ISSUE TITLE
Issue with URLSearchParams in IE11

### ISSUE THREAD

**Issue by tuespetre** [inexorabletash/polyfill#69]
If I create a `new URL('about:blank')` in the console in IE11, I can manipulate the `searchParams` and everything will work well.

However, I have a script that does the exact same thing and manipulating the `searchParams` seems to have no effect in IE11. 

Example of what I mean:

```
somePromiseReturningFunction().then(function (data) {
    var url = '/path/to/my/resource',
        options = {
            method: 'POST',
            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
            body: (function() {
                var params = new URL('about:blank').searchParams;
                params.append('my-field-1', data.field1);
                params.append('my-field-2', data.field2);
                return params.toString();
            })()
        };
    
    return fetch(url, options).then(function(r) {
        return someOtherPromiseReturningFunction();
    });                        
});
```

If I set a breakpoint in `polyfill.js` at [line 5046](https://github.com/inexorabletash/polyfill/blob/e46866b2fdf68c96558eaf1620a73020c4add2fd/polyfill.js#L5046), and examine things as each of the two values is set, I can verify a few things:

```
> window.field1scope = { param: this, pairs: pairs }
    [object Object]
> window.field2scope = { param: this, pairs: pairs }
    [object Object]
> window.field1scope.param === window.field2scope.param
    true
> window.field1scope.pairs === window.field2scope.pairs
    false
```

`this` is the actual `URLSearchParams` object.

**Comment by inexorabletash** [comment]
Thanks for the report!

Please try and make repro cases as minimal as possible. The second `append()` is actually throwing. I believe the reason it "seems to have no effect" is that your code is inside a Promise chain and you're not catching the rejection.

It looks like this behavior in IE11 is to blame:

```js
var a = document.createElement('a');
a.href = 'about:blank';
a.search = 'a';
a.search = 'a'; // throws Error with 'The URL is invalid'
```
I'll put in a workaround.
