### ISSUE TITLE
Rename lpad/rpad to padLeft/padRight, and ensure matching semantics

### ISSUE THREAD

**Issue by ljharb** [inexorabletash/polyfill#70]
The string padding proposal has been updated, so you'll want to rename your methods, and ensure they match the semantics of the proposal at https://github.com/ljharb/proposal-string-pad-left-right

**Comment by inexorabletash** [comment]
Thanks for the ping! I'll update when I have a chance.

Hrm, based on https://esdiscuss.org/topic/string-prototype-trimright-trimleft I wonder if these should be renamed to padStart  / padEnd ?

**Comment by ljharb** [comment]
TC39 discussed this in last week's meeting, and it was decided to stick with "left" and "right" - because of reduce/reduceRight, and because in JS strings, left/start/index zero are always identical, as are right/end/index length minus one. Based on that decision, padLeft/padRight are going to be consistent with that.
