### ISSUE TITLE
Publish polyfill as NPM module

### ISSUE THREAD

**Issue by thrucker** [inexorabletash/polyfill#71]
In order to use NPM as package manager it would be nice if this repository would be published as NPM module or at least to add a package.json.

**Comment by tracker1** [comment]
I agree that it would be nice to add this to npm, but with a note in the readme that says it should be used only for distribution packaging, not as a collection of modules.

**Comment by inexorabletash** [comment]
I'll try and get around to this. I have one of my other libraries published to NPM. With the caveat that I don't use this myself with any package managers, so I'll be relying on bug reports for when I get things wrong.

**Comment by inexorabletash** [comment]
Okay, published to https://www.npmjs.com/package/js-polyfills

Again, I don't use npm with this so I may require prodding to push updates.

**Comment by hpurmann** [comment]
Thanks a lot! :+1:

**Comment by inexorabletash** [comment]
Also, suggestions or PRs for the README are appreciated. This started off as "I wrote these for fun and/or personal use" so I haven't prioritized thinking about how to explain them to others, e.g. compared to es-shims etc
