### ISSUE TITLE
Update Object.values/entries to match stage 2 proposal

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/polyfill#74]
https://github.com/tc39/ecma262

https://github.com/ljharb/proposal-object-values-entries/blob/master/spec.md

**Comment by inexorabletash** [comment]
Done in 3a6061c2dde1d3a796fafe8c6f58cfe498df92ac

**Comment by zloirock** [comment]
@inexorabletash http://goo.gl/yEX3Ay

**Comment by inexorabletash** [comment]
Whoops, spoke to soon, Thanks, @zloirock
