### ISSUE TITLE
Is it possible to polyfill missing FormData methods?

### ISSUE THREAD

**Issue by teohhanhui** [inexorabletash/polyfill#76]
https://xhr.spec.whatwg.org/#interface-formdata

- delete
- get
- getAll
- has
- set
- iterable methods

**Comment by inexorabletash** [comment]
Not usefully, I don't think. Older implementations of `FormData` only have `append()` so there's no way to access the underlying data. It would be possible to override `append()` and track the data in JS which would get you `get`, `getAll`, `has` and the iterable methods. But `delete` and `set` would not be possible, and if initialized from a `HTMLFormElement` the fields from the form would unknown.

I suppose you could do it by completely replacing `FormData` with a JS implementation and hooking the consumers (XHR, ...), doing the conversion on demand, which is what the IE9- version in https://github.com/inexorabletash/polyfill/blob/master/xhr.js does, but that's pretty fragile.

**Comment by paulyn000** [comment]
I agree with this. this are very useful functions in terms of dynamic web development like drag and drop file upload and updating files or removing files from selected items

**Comment by inexorabletash** [comment]
Closing this out as "not practical"
