### ISSUE TITLE
KeyboardEvent.code

### ISSUE THREAD

**Issue by yukulele** [inexorabletash/polyfill#80]
On French keyboard ("azerty") pressing `a` key trigger `keyboardEvent.code = "KeyA"` instead of English ("qwerty") equivalent `"KeyQ"`.

**Comment by beckyconning** [comment]
surely thats correct? if you press the a then `keyboardEvent.code` should be `"KeyA"`.

**Comment by yukulele** [comment]
No, the aim of ```keyboardEvent.code``` is to know the physical position of a key.
Usage exemples
* game with "WASD" key (coresponding key on azerty keyboard are "ZQSD"
* piano keyboard

https://developer.mozilla.org/en/docs/Web/API/KeyboardEvent/code

**Comment by inexorabletash** [comment]
Yep. Alas, not much that can be done w/o some way to determine the keyboard layout. This is why a native implementation is needed.

**Comment by inexorabletash** [comment]
I'm not sure of a way to fix this, which is why the keyboardEvent polyfill is pretty limited. It would require knowing the keyboard layout (which isn't exposed to script) and maintaining a mapping (which is doable but unpleasant).

Ideas welcome, but closing this out as "not practical" for now.
