### ISSUE TITLE
ES5 getOwnPropertyNames

### ISSUE THREAD

**Issue by panyifei** [inexorabletash/polyfill#81]
Hi,I read your code about the `getOwnPropertyNames` function in es5.js.I found  this polyfill can't cover 

```javascript
var arr = ['a', 'b', 'c'];
console.log(Object.getOwnPropertyNames(arr).sort()); // logs '0,1,2,length'
```

you can check the doc [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames#Examples)

because `length` in array isn't enumerable.

**Comment by inexorabletash** [comment]
Yes, the polyfill's functionality is limited. Somewhat by definition, it is not possible to enumerate non-enumerable properties without a native `getOwnPropertyNames`.
