### ISSUE TITLE
IEEE754 conversion does not match the native 

### ISSUE THREAD

**Issue by zloirock** [inexorabletash/polyfill#82]
Currently, I write Typed Arrays polyfill for `core-js`, but I'm not an expert in IEEE754, so, at first, I tried to explore available functions for IEEE754 conversions. I tried your functions, but packing 32-bit float here does not match the native. For example:
```js
// native:
new Float32Array([2147483647]); // => [2147483648]
new Uint8Array(new Float32Array([2147483647]).buffer); // => [0, 0, 0, 79]
// your:
new Float32Array([2147483647]); // => [2147483904]
new Uint8Array(new Float32Array([2147483647]).buffer); // => [1, 0, 0, 79]
```
Conversions from [this  library](https://github.com/feross/ieee754) works fine, but writing my test case still in progress.

**Comment by inexorabletash** [comment]
Ugh, thanks. This looks like one of those "how did it ever work?" cases, but I also haven't revisited all of the code. Can you give this change a whirl with your test cases?

```diff
         if (f / pow(2, fbits) >= 2) {
           e = e + 1;
-          f = 1;
+          f = pow(2, fbits);
         }
```

**Comment by zloirock** [comment]
Yep, current test case passed, but, as I said, it's still not finished :)

**Comment by inexorabletash** [comment]
"closed" but I welcome more test cases!
