### ISSUE TITLE
missing getComputedStyle, FileReader

### ISSUE THREAD

**Issue by paulyn000** [inexorabletash/polyfill#87]
I've tried using this on my project and tried to run on old ie, `getComputedStyle` does not work and `FileReader`. I would like to know if this has been polyfied already

**Comment by inexorabletash** [comment]
`getComputedStyle` is both fairly niche (well, I've never needed it) and a polyfill is nontrivial and an approximation at best. https://github.com/jonathantneal/Polyfills-for-IE8/blob/master/getComputedStyle.js seems reasonable, but I'm not going to attempt something similar.

`FileReader` is basically impossible without replacing all of Blob/File/XHR and would not be useful for cases like `<input type=file>`, so I'm not going for that either.
