### ISSUE TITLE
use github's fetch polyfill.

### ISSUE THREAD

**Issue by OneOfOne** [inexorabletash/polyfill#91]
Mainly for the credentials support.

- https://github.com/github/fetch

**Comment by inexorabletash** [comment]
I added credentials support. Can you give it a whirl and see if there's anything else you're missing? If not I'll tag and push a release.

**Comment by OneOfOne** [comment]
LGTM, but you left a stray console.log @ https://github.com/inexorabletash/polyfill/commit/2ef98b2a5f5c256a2b3cac769b3374f1d749f228#diff-56035df8f377cf2219374cd504d3b8caR615

Remove that and release, thank you for the update.

**Comment by inexorabletash** [comment]
Whoops! Thanks, fixed and pushed.
