### ISSUE TITLE
fix polyfill

### ISSUE THREAD

**Issue by paulyn000** [inexorabletash/polyfill#94]
Please fix `addEventListener` and others to support IE7 or etc. It should be a polyfill not another implementation e.g `addEventListener` should not be `addEvent`, also the `classList`, it shouldn't be `relList`

**Comment by inexorabletash** [comment]
IE7 and below don't support adding methods/properties to the prototypes of elements, so this isn't possible.

**Comment by Mouvedia** [comment]
@inexorabletash https://gist.github.com/jonathantneal/5ca2cf0d5b0c39c2450d

**Comment by inexorabletash** [comment]
Yes, you can iterate over all elements and attach a method to them. That doesn't help for dynamically created objects. So you end up having to modify how you're creating nodes and/or modifying the DOM, at which point it's not particularly helpful since you're not writing raw DOM code anyway.

**Comment by inexorabletash** [comment]
(Practically speaking, the only useful thing to do with IE<11 is pop a warning telling users that they're using a horrifically insecure browser and should immediately disconnect from the Internet, so I'm not going to make contortions to the code to support anything pre-IE8.)
