### ISSUE TITLE
</body> tag in string literal

### ISSUE THREAD

**Issue by jlesueur** [inexorabletash/polyfill#97]
https://github.com/inexorabletash/polyfill/blob/master/url.js#L273

If URL ends up being included directly in a ```<script>``` tag inside the head, it produces the following line
```html
<script type="text/javascript">
...
doc.write('<head></head><body></body>');
...
</script>
```
It's common to avoid outputing a closing body tag, even with a javascript string:
```
doc.write('<head><'+ '/head><body><' + '/body>');
```
Is it possible to incorporate a change like this?

**Comment by inexorabletash** [comment]
That is harmless unless `</script>` itself occurs in the script. Can you demonstrate an actual failure in a browser?

It's easy enough to change it to `"<head><\/head><body><\/body>"` but it also shouldn't be necessary.

**Comment by jlesueur** [comment]
The failure is actually due to a bug in another tool. NewRelic automatically injects javascript into a page for tracking purposes, and looks for a </body> in the output, regardless of context. Obviously, that's not really your problem, but it's also simple enough to work around with your proposed change. Thanks for your time, whichever way you decide to go.

**Comment by inexorabletash** [comment]
Okay, pushed a fix. Let me know if this works for you, and if so I'll tag/push a release.

**Comment by jlesueur** [comment]
Thanks, fixes my issue.
